server:
  port: 8082

service:
  name: B
  description: Bank B REST microservice
  address: host.docker.internal:8082

  network-name: network
  network-address: host.docker.internal:8083

  logger-name: logger
  logger-address: host.docker.internal:8084